/**
 * EIC (European Innovation Council) standard taxonomy.
 * This is the basic taxonomy used across the platform. Not dynamic — fixed list.
 * DB seed: drizzle/migrations/0006_seed_eic_taxonomy.sql
 */

export interface EICCategory {
  name: string;
  subcategories: string[];
}

export const EIC_TAXONOMY: EICCategory[] = [
  {
    name: "Agriculture",
    subcategories: [
      "Agronomy",
      "Animal and Dairy science",
      "Aquaculture",
      "Aquatic biology, Hydrobiology",
      "Fishery",
      "Forestry",
      "Horticulture, viticulture",
      "Husbandry",
      "Paper and wood",
      "Plant breeding and plant protection",
      "Precision agriculture",
      "Soil management",
    ],
  },
  {
    name: "Biotechnology",
    subcategories: [
      "Biochemistry",
      "Bacteriology",
      "Bioeconomy",
      "Biohazards, biological containment, biosafety, biosecurity",
      "Bioinformatics",
      "Bioproducts (biomaterials, bioplastics, biofuels)",
      "Bioremediation, biodegradation",
      "Biotechnology (non-medical), bioreactors, applied microbiology",
      "DNA synthesis, modification, repair, recombination",
      "Genetics and heredity",
      "Human biology",
      "Microbiology",
      "Neurochemistry and neuropharmacology",
      "Plant sciences, botany",
      "Reproductive biology",
      "Serology",
      "Tissue culture",
      "Zoology",
      "Bioprocessing technologies (biocatalysis, fermentation)",
    ],
  },
  {
    name: "Construction, Civil engineering, Infrastructures",
    subcategories: [
      "Glass, ceramics & construction material",
      "Architecture, smart buildings, smart cities",
      "Civil engineering, maritime/hydraulic engineering",
      "Construction engineering, Municipal and structural engineering",
      "Low/nearly zero & energy positive buildings",
      "Urban studies (Planning and development)",
    ],
  },
  {
    name: "Consumer products and services",
    subcategories: [
      "Distribution and logistics",
      "Electronic commerce (eCommerce)",
      "Household products",
      "Leisure products",
      "Leisure services",
      "Personal products and services",
      "Retail, wholesale or distribution",
      "Service innovation",
      "Supply chain management",
      "Textiles, apparel and luxury goods",
      "Tourism / Travel",
    ],
  },
  {
    name: "Earth and related environmental sciences",
    subcategories: [
      "Environmental protection",
      "Atmospheric chemistry, air pollution",
      "Circular economy",
      "Climatology and climate change",
      "Decontamination and de-pollution",
      "Ecology",
      "Environmental and Green Technologies",
      "Flood forecasting",
      "Geographical information systems, cartography",
      "Geo-information and spatial data analysis",
      "Geology, tectonics, volcanology",
      "Hydrology",
      "Marine biology",
      "Marine ecosystems and processes",
      "Meteorology",
      "Mineralogy",
      "Natural resources exploration and exploitation",
      "Waste management",
      "Waste recycling",
      "Wastewater treatment",
      "Water",
    ],
  },
  {
    name: "Education and Culture",
    subcategories: [
      "Education",
      "Psychology",
      "Social Media",
      "Arts (performing arts, music)",
      "Behavioural change",
      "Cultural heritage, cultural memory",
      "Design innovation",
      "Informal education",
      "Innovation and diversity",
      "Languages and Literature",
      "Life long learning",
      "Media and communications",
      "Social issues",
      "Teaching materials",
    ],
  },
  {
    name: "Energy",
    subcategories: [
      "Biodiesel",
      "Bioenergy",
      "Biofuels",
      "Biogas",
      "Biomass",
      "Biomethane",
      "Domestic appliances",
      "Electricity Transmission/Distribution",
      "Electrochemistry, batteries and fuel cells",
      "Energy Economics",
      "Energy Efficiency",
      "Energy management",
      "Energy systems (production, distribution, application)",
      "Smart energy, smart grids, wireless energy transfer",
      "Fuel Production & Distribution",
      "Hydrogen",
      "Low/zero carbon communities",
      "Natural gas",
      "Photovoltaics",
      "Renewable energy sources",
      "Solar cooling",
      "Solar thermal",
    ],
  },
  {
    name: "Engineering and Technology",
    subcategories: [
      "Manufacturing and processing",
      "Acoustics",
      "Audio engineering, reliability analysis",
      "Automation and control systems",
      "Chemical engineering, technical chemistry",
      "Communication engineering and systems",
      "Control engineering",
      "Electrical and electronic engineering",
      "Electromagnetism",
      "Electromechanical engineering",
      "Electronics, photonics",
      "Graphene, layered material",
      "Industrial bioengineering",
      "Materials engineering",
      "Mechanical engineering",
      "Metallurgy",
      "Metrology and measurement",
      "Micro (system) engineering",
      "Nanotechnology, nano-materials",
      "Novel Materials",
      "Ocean engineering",
      "Optics (laser optics and quantum optics)",
      "Organic electronics",
      "Photonics",
      "Porous Materials",
      "Production technology, process engineering",
      "Propulsion systems engineering",
      "Robotics",
      "Semiconductors",
      "Solid state materials",
      "Superconductivity",
      "Thermodynamics",
    ],
  },
  {
    name: "Food and Beverages",
    subcategories: [
      "Agricultural products",
      "Brewers",
      "Distillers and vintners",
      "Food additives",
      "Food contamination",
      "Food packaging",
      "Food preservation",
      "Food quality",
      "Food safety",
      "Food storage",
      "Food technology",
      "Secure food chain and wealth products",
      "Soft drinks",
    ],
  },
  {
    name: "Health",
    subcategories: [
      "Ageing",
      "Biomarkers",
      "Cardiac and Cardiovascular systems",
      "Clinical medicine",
      "Critical care medicine and Emergency medicine",
      "Dentistry, oral surgery and medicine",
      "Dermatology and venereal diseases",
      "Diagnostic tools (genetic, imaging)",
      "Drugs",
      "eHealth",
      "Endocrinology and metabolism",
      "Gene therapy",
      "Geriatrics and gerontology",
      "Healthcare system",
      "Health-related biotechnology",
      "Human genetics",
      "Immunology",
      "Infectious diseases",
      "Medical devices",
      "Neurodegenerative disorders",
      "Obstetrics and gynaecology",
      "Oncology",
      "Ophthalmology",
      "Orthopaedics",
      "Paediatrics",
      "Pathology",
      "Patient care",
      "Personalised treatment",
      "Pharmacology and pharmacy",
      "Psychiatry",
      "Radiology, nuclear medicine and medical imaging",
      "Rehabilitation",
      "Respiratory systems",
      "Rheumatology",
      "Robotics for healthcare",
      "Surgery",
      "Toxicology",
      "Transplantation",
      "Urology and nephrology",
      "Vaccines",
      "Virology",
      "Wellbeing",
    ],
  },
  {
    name: "Information and Communication Technology (ICT)",
    subcategories: [
      "Artificial intelligence",
      "Blockchain and Distributed Ledger Technology (DLT)",
      "Internet of Things, embedded systems",
      "Big data",
      "Extended Reality (XR)",
      "Advanced computing",
      "Algorithms and complexity",
      "Unmanned aircraft (Drone)",
      "Cloud computing",
      "Communication networks, media",
      "Communication technology, high-frequency technology",
      "Computational engineering",
      "Computer graphics",
      "Computer hardware and architecture",
      "Computer sciences, information science",
      "Cryptology, security, privacy, quantum crypto",
      "Cyber-physical systems",
      "Cybersecurity",
      "Data protection and privacy",
      "Digital games, gamification, serious games",
      "Digital services",
      "E-learning, user modelling, collaborative systems",
      "5G network technology",
      "Fintech (Financial technology)",
      "Human computer interaction and interface",
      "Assistive Technologies",
      "Internet Services & Applications",
      "Machine learning, statistical data processing",
      "Networks (communication, sensor, robots)",
      "Neuroimaging and computational neuroscience",
      "Ontologies, neural networks, genetic programming",
      "Scientific computing, simulation and modelling",
      "Software engineering, operating systems",
    ],
  },
  {
    name: "Public Sector Innovation",
    subcategories: [
      "Business model innovation",
      "Corporate Social responsibility",
      "Human resource management",
      "Open data",
      "Open innovation",
      "Public administration innovation",
      "Social innovation",
    ],
  },
  {
    name: "Security",
    subcategories: [
      "Chemical, Biological, Radiological and Nuclear (CBRN) protection",
      "Crisis management",
      "Critical infrastructure, emergency systems",
      "Detection technology",
      "Explosives removal",
      "Forensic technologies",
      "Identification",
      "Information Security Technologies",
      "Interoperable secured communications",
      "Navigation, guidance, control and tracking",
      "Networks and information security systems",
      "Protection",
      "Risk management",
      "Search and detection",
      "Surveillance",
    ],
  },
  {
    name: "Space",
    subcategories: [
      "Earth Observation / Services and applications",
      "Flight Dynamics / Position, Navigation, and Timing",
      "Global Satellite Navigation System (GNSS)",
      "Instrumentation - telescopes, detectors",
      "Launchers",
      "On-Board Data Systems",
      "Orbital transportation and re-entry systems",
      "Remote sensing",
      "RF Payload and Systems",
      "Satellites and Probes",
      "Space data exploitation",
      "Space Debris",
      "Space services and products",
      "Spacecraft",
      "Supporting Propulsion Technologies",
      "Telecommunications",
    ],
  },
  {
    name: "Transport and Mobility",
    subcategories: [
      "Aircraft Avionics, Systems & Equipment",
      "Airports",
      "Automation",
      "Automotive",
      "Logistics",
      "Maritime and infrastructure",
      "Maritime transport",
      "Multimodality",
      "Network infrastructures",
      "Propulsion",
      "Rail infrastructure",
      "Rail Transport",
      "Road infrastructure",
      "Road transport",
      "Sea vessels",
      "Sustainable transport",
      "Air traffic management (ATM)",
      "Transport engineering",
      "Urban transport",
      "Vehicle Technology",
    ],
  },
];
