// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykubdeoejdtpivfcweoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWJkZW9lamR0cGl2ZmN3ZW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTI3NjEsImV4cCI6MjA3MzU4ODc2MX0.50smA3TNVzKeztz5HbFnaAoXJkSgg5Gn5iiE5OfPbcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});